- name: connect ssh and launch staging version of deploy-admin.sh
  hosts: server1
  remote_user: ubuntu

  tasks:
  - name: clear folder before sync
    shell: rm -rf kubernetes-showtime-project/build_front_admin_staging/*

  - name: Rsync CI folder to remote staging folder
    synchronize:
      src: /var/www/html/showtime_WEB/dist/
      dest: /home/ubuntu/kubernetes-showtime-project/build_front_admin_staging/
      recursive: yes
      rsync_opts:
        - "--delete"
        - "--omit-dir-times"
        - "--no-perms"
  - name: launch deploy script for staging admin front
    shell: cd kubernetes-showtime-project/host_staging && sudo bash deploy-admin.sh
    register: result
